### PR TITLE
fix(buildnode): #30 fix buildnode exception

### LINKED ISSUE #30: (build.sh) BuildNode master/dev ko
A revoir le script car si on fait buildNode avec une branche autre que master/dev, il y aura une exception

### PR DESCRIPTION
**Pull request by AyaNADINI**
## Describe your changes
The issue contains the description : https://github.com/OPEN-ENT-NG/rbs/issues/30
Exception :  
Entcore problem, what is displayed on the VM :
[This is most likely not a problem with npm itself.
In most cases you or one of your dependencies are requestion a package version that doesn't exist]
I tried to add a screenshot of the error but it is not possible.

## Checklist tests
We can check by compiling the buildNode (./build.sh buildNode) in our module (rbs) and according to our branch (if it is master or a branch that is part of the entcore or if it is a totally different branch)

## Issue ticket number and link
30 : https://github.com/OPEN-ENT-NG/rbs/issues/30

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -46,13 +46,24 @@ buildNode () {
...
   else
       echo "[buildNode] Use entcore tag $BRANCH_NAME"
-      case `uname -s` in
-        MINGW*)
-          docker-compose run --rm -u "$USER_UID:$GROUP_GID" node sh -c "npm install --no-bin-links && npm rm --no-save entcore && npm install --no-save entcore@$BRANCH_NAME && node_modules/gulp/bin/gulp.js build"
-          ;;
-        *)
-          docker-compose run --rm -u "$USER_UID:$GROUP_GID" node sh -c "npm install && npm rm --no-save entcore && npm install --no-save entcore@$BRANCH_NAME && node_modules/gulp/bin/gulp.js build"
-      esac
+      tester_var=$(npm dist-tags ls entcore)
```
Comment (JinDouang) [inline build.sh]: à revoir le nom de la variable

**Review by JinDouang — CHANGES_REQUESTED** [review]

**Review by JinDouang — APPROVED** [review]

**Review by alicedraillard — APPROVED** [review]

**Review by qperie — APPROVED** [review]

**Review by aymericdevriesere — APPROVED** [review]

**Review by flmartineau — APPROVED** [review]

**Review by BastienBenard — APPROVED** [review]
